services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    working_dir: /app
    command: python3 search_bm25.py --index /app/index --query "index compression"

